version: "3.7"
networks:
  default:
    internal: true
  gateway:
    external: true
services:
  homarus:
    restart: ${RESTART_POLICY:-unless-stopped}
    image: ${REPOSITORY:-islandora}/homarus:${TAG:-latest}
  houdini:
    restart: ${RESTART_POLICY:-unless-stopped}
    image: ${REPOSITORY:-islandora}/houdini:${TAG:-latest}
  hypercube:
    restart: ${RESTART_POLICY:-unless-stopped}
    image: ${REPOSITORY:-islandora}/hypercube:${TAG:-latest}
  milliner:
    restart: ${RESTART_POLICY:-unless-stopped}
    image: ${REPOSITORY:-islandora}/milliner:${TAG:-latest}
    environment:
      MILLINER_FEDORA6: ${FEDORA_6}
    networks:
      default:
      gateway:
  recast:
    restart: ${RESTART_POLICY:-unless-stopped}
    image: ${REPOSITORY:-islandora}/recast:${TAG:-latest}
